version: '3'
services:

  monitoring-service:
    build:
      context: ./monitoringService/
    networks:
      - private-network
    container_name: monitoring-service

  log-service:
    build:
      context: ./logService/
    networks:
      - private-network
    container_name: log-service

  auth-service:
    build:
      context: ./authService/
    networks:
      - private-network
    container_name: auth-service
    
  user-service:
    build:
      context: ./userService/
    networks:
      - private-network
    container_name: user-service

  order-service:
    build:
      context: ./orderService/
    networks:
      - private-network
    container_name: order-service

  restaurant-service:
    build:
      context: ./restaurantService/
    networks:
      - private-network
    container_name: restaurant-service

  ticket-service:
    build:
      context: ./ticketService/
    networks:
      - private-network
    container_name: ticket-service

  review-service:
    build:
      context: ./reviewService/
    networks:
      - private-network
    container_name: review-service

  websocket-service:
    build:
      context: ./websocketService/
    networks:
      - private-network
    container_name: websocket-service

  stat-service:
    build:
      context: ./statService/
    networks:
      - private-network
    container_name: stat-service

  nginx-rp:
    build:
      context: ./reverseProxy/
    ports:
      - 80:80
    networks:
      - private-network
    container_name: nginx-rp

  nginx-prometheus-exporter:
    image: 
      nginx/nginx-prometheus-exporter:0.9.0
    command:
      - -nginx.scrape-uri=http://nginx-rp/basic_status
    depends_on:
      - nginx-rp
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
          ip_range: 172.20.0.0/24